### ISSUE TITLE
ouput was empty file

### ISSUE THREAD

**Issue by zhangyiyan001** [suvojit-0x55aa/A2S2K-ResNet#2]
`record.record_output(
    OA, AA, KAPPA, ELEMENT_ACC, TRAINING_TIME, TESTING_TIME,
    './report/' + 'SSRNpatch:' + str(img_rows) + '_' + Dataset + 'split' +
    str(VALIDATION_SPLIT) + 'lr' + str(lr) + PARAM_OPTIM + '.txt')`
`Utils.generate_png(
    all_iter, net, gt_hsi, Dataset, device, total_indices,
    './classification_maps/' + 'SSRNpatch:' + str(img_rows) + '_' + Dataset +
    'split' + str(VALIDATION_SPLIT) + 'lr' + str(lr) + PARAM_OPTIM)`
the report and classification folder need to be created additionally,Right?
And there is no output '.txt' and '.png'file generated as program descripition.

**Comment by zhangyiyan001** [comment]
I have solved this bug.
`Utils.generate_png(all_iter, net, gt_hsi, Dataset, device, total_indices,'./classification_maps/' + 'S3KAIResNetpatch:' + str(img_rows) + '_' +Dataset + 'split' + str(VALIDATION_SPLIT) + 'lr' + str(lr) + PARAM_OPTIM +'_kernel_' + str(PARAM_KERNEL_SIZE))`
The colon can not exist in the folder.when I delete the colon, that's fine!

**Comment by DHX209** [comment]
THANKS
